### PR TITLE
use p256k1 from crates and a frost rev with the same dep

### PR DESCRIPTION
**Pull request by xoloki**

### CODE REVIEW

**Review by igorsyl — APPROVED** [review]
LGTM. 

Curious why does core-eng depend directly on p256k1?

**Review by sergey-shandar — APPROVED** [review]

**Comment by xoloki** [comment]
> LGTM.
> 
> Curious why does core-eng depend directly on p256k1?

There's a couple of places where we use scalars and points explicitly

**Comment by netrome** [comment]
> > LGTM.
> > Curious why does core-eng depend directly on p256k1?
> 
> There's a couple of places where we use scalars and points explicitly

 @xoloki if this is necessary, should we consider re-exporting these types within the FROST crate to make it more approachable for new adopters?

**Comment by xoloki** [comment]
> > > LGTM.
> > > Curious why does core-eng depend directly on p256k1?
> > 
> > 
> > There's a couple of places where we use scalars and points explicitly
> 
> @xoloki if this is necessary, should we consider re-exporting these types within the FROST crate to make it more approachable for new adopters?

I think that's an excellent idea.

**Pull request merged**
