### PR TITLE
[Chores] Add toc for dev guide

### LINKED ISSUE #59: stacks-dev-guide: add link to instructions on how to run a radon node
https://twitter.com/judecnelson/status/1623151711530504192

https://gist.github.com/jcnelson/c5f43cbefba3727dcccf5a95209b60fc

### PR DESCRIPTION
**Pull request by empeje**
Following my observation when working with the #143 I've added TOC for the dev guide.

Closes #59

### CODE REVIEW

**Review by jferrant — APPROVED** [review]
Nice improvement. LGTM

**Comment by empeje** [comment]
This is the guide to generate ToC, I added in the WikI https://github.com/Trust-Machines/core-eng/wiki/How-to-generate-ToC-from-Markdown-in-IntelliJ

cc: @igorsyl

**Comment by igorsyl** [comment]
Can we add instructions to the doc on updating the TOC programmatically?

**Review by igorsyl — APPROVED** [review]
let's rename stacks-dev-guide to docs.

**Pull request merged**
