### PR TITLE
Wrap error type

### PR DESCRIPTION
**Pull request by aryzing**
[As suggested](https://github.com/Trust-Machines/core-eng/pull/318#discussion_r1184681822), this PR wraps the error types.

Depends on 

- https://github.com/Trust-Machines/p256k1/pull/65
- https://github.com/Trust-Machines/wsts/pull/1

Closes https://github.com/Trust-Machines/core-eng/issues/373

### CODE REVIEW

**Comment by xoloki** [comment]
Ok @aryzing `wsts-1.1.0` published: https://crates.io/crates/wsts

**Comment by xoloki** [comment]
> I'm not sure why `cargo test` is failing,
> 
> ```
> ---- coordinator::test::integration_test stdout ----
> thread 'coordinator::test::integration_test' panicked at '../target/debug/relay-server failed to start', test-utils/src/lib.rs:62:33
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Full stacktrace
> I don't have bitcoin core or deno on my current machine, are those required to run the test?

Did you do a `cargo build` first @aryzing ?

**Comment by aryzing** [comment]
> Did you do a cargo build first @aryzing ?

I didn't. Now I have plus installed bitcoind + deno and all tests pass. I'll try to fix the clippy issues too.

**Comment by aryzing** [comment]
Alright, clippy issues fixed, we should be good to go now, let me know if there's anything else that needs to be addressed

**Comment by xoloki** [comment]
> Alright, clippy issues fixed, we should be good to go now, let me know if there's anything else that needs to be addressed

Just need one more review then we can merge.

**Comment by xoloki** [comment]
> Alright, clippy issues fixed, we should be good to go now, let me know if there's anything else that needs to be addressed

Actually @aryzing you need to rebase on upstream main, please rebase not merge.

**Review by jferrant — APPROVED** [review]

**Comment by aryzing** [comment]
Rebased ✅

**Pull request merged**
