### PR TITLE
proposal

### PR DESCRIPTION
**Pull request by sergey-shandar**

### CODE REVIEW

**Review by netrome — APPROVED** [review]
Nice, thanks!

**Comment by sergey-shandar** [comment]
> Nice, thanks!

Feel free to merge it to your branch or cherry-pick the code.

**Comment by netrome** [comment]
> > Nice, thanks!
> 
> Feel free to merge it to your branch or cherry-pick the code.

Following our discussion in Discord I'll rebase ;)

**Comment by igorsyl** [comment]
@sergey-shandar Please let's use descriptive PR names. Thank you!

**Comment by netrome** [comment]
> @sergey-shandar Please let's use descriptive PR names. Thank you! I envision an AI bot that can read the commits and generate the title automatically. We can do this today.

@igorsyl this PR was just a proposal to my PegQueue implementation, so I don't think we should require it to follow our high standards for "real" PRs :wink:

**Pull request closed without merging**
